#!/bin/bash

# loop until the Consul service is running
while true; do
  status=$(systemctl is-active consul)
  if [ "$status" == "active" ]; then
    break
  fi
  echo "[WARN] waiting for Consul to start..."
  sleep 1  # wait for 1 seconds before checking again
done
