#!/bin/bash

# loop until the Nomad service is running
while true; do
  status=$(systemctl is-active nomad)
  if [ "$status" == "active" ]; then
    break
  fi
  echo "[WARN] waiting for Nomad to start..."
  sleep 1  # wait for 1 seconds before checking again
done
