#!/bin/bash

set -e

echo ""
echo "============================================================="
echo "[INFO] NOMAD_VERSION.................. $NOMAD_VERSION"
echo "[INFO] CONSUL_VERSION................. $CONSUL_VERSION"
echo "[INFO] VAULT_VERSION.................. $VAULT_VERSION"
echo "[INFO] NETBIRD_VERSION................ $NETBIRD_VERSION"
echo "============================================================="
echo ""

# function to check if a directory contains configuration files
start_if_config_exists() {
  local service=$1
  local config_dir=$2
  local version=$3
  if [ -d "$config_dir" ] && [ "$(ls -A "$config_dir")" ]; then
    echo "[INFO] Configuration files found for $service. Starting $service..."
    hashi-up $service install --local --version $version --skip-start --config-file $config_dir/config.hcl
    sed -i 's/^User=consul/User=root/' /etc/systemd/system/$service.service
    sed -i 's/^Group=consul/Group=root/' /etc/systemd/system/$service.service
    sed -i 's/^User=nomad/User=root/' /etc/systemd/system/$service.service
    sed -i 's/^Group=nomad/Group=root/' /etc/systemd/system/$service.service
    sed -i 's/^User=vault/User=root/' /etc/systemd/system/$service.service
    sed -i 's/^Group=vault/Group=root/' /etc/systemd/system/$service.service
    systemctl enable $service.service
    systemctl start $service
  else
    echo "[WARN] No configuration files found for $service. Skipping $service..."
  fi
}

start_netbird_if_config_exists() {
  service="netbird"
  local config_dir=$1
  local version=$2
  if [ -d "$config_dir" ] && [ "$(ls -A "$config_dir")" ]; then
    echo "[INFO] Configuration files found for $service. Starting $service..."
    docker volume create netbird_agent_data
    docker run --name netbird-agent --rm -d \
      --privileged \
      --network "host" \
      --env-file $config_dir/config.env \
      -v netbird_agent_data:/etc/netbird \
      netbirdio/netbird:$version
  else
    echo "[WARN] No configuration files found for $service. Skipping $service..."
  fi
}

# start Netbird if config files exist
start_netbird_if_config_exists "/netbird/config" $NETBIRD_VERSION
# start Vault if config files exist
start_if_config_exists "vault" "/vault/config" $VAULT_VERSION
# start Consul if config files exist
start_if_config_exists "consul" "/consul/config" $CONSUL_VERSION
# start Nomad if config files exist
start_if_config_exists "nomad" "/nomad/config" $NOMAD_VERSION
echo ""