[package]
name = "ministack"
version = "1.0.2"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tera = "1.17"
include_dir = "0.7"
