version: '3'

tasks:

  certificats-generate:
    internal: true
    silent: true
    cmds:
      - |
        datacenter="$(cat {{.CONFIG_FILE}} | yq -r '.datacenter')"
        echo "[INFO] datacenter is $datacenter"
        if [ -d "certs/$datacenter" ]; then
          echo "[WARN] certificats alrady exists, we skip!"
          exit 0
        fi
        echo "[INFO] generating certificats for consul"
        mkdir -p certs/$datacenter
        cd certs/$datacenter
        consul tls ca create -domain=consul
        consul tls cert create -server -dc=$datacenter -domain=consul

  certificats-remove:
    internal: true
    silent: true
    cmds:
      - |
        echo "[INFO] deleting all certificats"
        datacenter="europe-paris"
        rm -rf certs/$datacenter

  networks-create:
    internal: true
    silent: true
    cmds:
      - |
        echo "[INFO] creating docker networks"
        declare -A networks
        networks=(
          ["ministack-global"]="10.1.0.0/24 ministack"
        )
        network_exists() {
          local network_name=$1
          docker network ls --filter name=^${network_name}$ --format "{{.Name}}" | grep -wq "${network_name}"
        }
        for network in "${!networks[@]}"; do
          IFS=' ' read -r subnet iface_prefix <<< "${networks[$network]}"
          if network_exists "$network"; then
            echo "[WARN] network '$network' already exists. Skipping creation"
          else
            echo "[INFO] creating network '$network'..."
            docker network create \
              --driver=bridge \
              --subnet="$subnet" \
              --opt "com.docker.network.container_iface_prefix=$iface_prefix" \
              "$network"
            if [[ $? -eq 0 ]]; then
              echo "[INFO] network '$network' created successfully"
            else
              echo "[ERROR] failed to create network '$network'"
              exit 1
            fi
          fi
        done

  templates-generate:
    internal: true
    silent: true
    cmds:
      - |
        echo "[INFO] generating docker compose files"
        if [ -d "build" ]; then
          rm -rf build
        fi
        echo "[INFO] config file to use: {{.CONFIG_FILE}}"
        gomplate --input-dir=templates --output-dir=build --datasource config={{.CONFIG_FILE}}

  services-start:
    internal: true
    silent: true
    cmds:
      - |
        echo "[INFO] starting docker compose services"
        docker compose --file build/cluster.yaml up -d

  services-stop:
    internal: true
    silent: true
    cmds:
      - |
        echo "[INFO] removing docker compose services"
        docker compose --file build/cluster.yaml down

  ministack-dry-run:
    cmds:
      - task: templates-generate
        vars:
          CONFIG_FILE: '{{.CLI_ARGS}}'

  ministack-start:
    cmds:
      - task: networks-create
      - task: certificats-generate
        vars:
          CONFIG_FILE: '{{.CLI_ARGS}}'
      - task: templates-generate
        vars:
          CONFIG_FILE: '{{.CLI_ARGS}}'
      - task: services-start

  ministack-stop:
    cmds:
      - task: templates-generate
        vars:
          CONFIG_FILE: '{{.CLI_ARGS}}'
      - task: services-stop
      - task: certificats-remove
        vars:
          CONFIG_FILE: '{{.CLI_ARGS}}'
