name: 'hashistack-dev'
datacenter: 'europe-paris'
image:
  repository: 'ghcr.io/gperreymond/hashibase'
  tag: 'main'

services:
  consul:
    enabled: true
    version: '1.20.1'
    replicas: 1
  nomad:
    enabled: true
    version: '1.9.4'
    replicas: 1
    clients:
      - name: worker-pikachu
      - name: worker-ronflex
  vault:
    enabled: false

plugins:
  traefik:
    enabled: true
    version: '3.3.1'
