name: hashistack-dev
datacenter: 'europe-paris'
image:
  repository: 'ghcr.io/gperreymond/hashibase'
  tag: 'main'

services:
  consul:
    version: '1.20.1'
    enabled: true
    replicas: 1
  nomad:
    version: '1.9.4'
    enabled: true
    replicas: 1
  vault:
    enabled: false

plugins:
  traefik:
    enabled: true
    version: '3.2.3'
