{%- set nomad_replicas = 1 -%}
{%- if services.nomad.bootstrap_expect -%}
{%- set nomad_replicas = services.nomad.bootstrap_expect -%}
{%- endif -%}

{%- set consul_replicas = 1 -%}
{%- if services.consul.bootstrap_expect -%}
{%- set consul_replicas = services.consul.bootstrap_expect -%}
{%- endif -%}

{%- if 
  services.consul.enabled or
  plugins.prometheus.enabled
%}
services:
  {%- if plugins.prometheus.enabled %}
  prometheus-reloader:
    image: 'bash:5.2.37'
    container_name: 'prometheus-reloader'
    restart: unless-stopped
    command: |
      bash -c "
        apk add curl > /dev/null 2>&1
        curl -X POST http://prometheus:9090/-/reload
        sleep 60
      "
    networks:
      ministack: {}
    depends_on:
      prometheus:
        condition: service_healthy
  {%- endif %}
  {%- if services.consul.enabled %}
  post-start-consul:
    image: 'bash:5.2.37'
    container_name: 'post-start-consul'
    restart: unless-stopped
    command: |
      bash -c "
        apk add curl > /dev/null 2>&1
        echo ""
        bash /scripts/consul/01-apply-default-intension.sh
        {%- if plugins.traefik.enabled %}
        bash /scripts/consul/02-register-traefik.sh
        {%- endif %}
        sleep 60
      "
    volumes:
      - './scripts:/scripts'
    networks:
      ministack: {}
    depends_on:
      {%- for i in range(start=1, end=consul_replicas+1) %}
      'consul-server-{{ i }}':
        condition: service_healthy
      {%- endfor %}
  {%- endif %}
{%- else %}
{%- endif %}
