{%- set nomad_replicas = 1 -%}
{%- if services.nomad.replicas -%}
{%- set nomad_replicas = services.nomad.replicas -%}
{%- endif -%}

{%- set consul_replicas = 1 -%}
{%- if services.consul.replicas -%}
{%- set consul_replicas = services.consul.replicas -%}
{%- endif -%}

{%- if services.nomad.enabled or services.consul.enabled %}
services:
  {%- if services.nomad.enabled %}
  post-start-nomad:
    image: 'bash:5.2.37'
    container_name: 'post-start-nomad'
    restart: unless-stopped
    command: |
      bash -c "
        apk add curl > /dev/null 2>&1
        sleep 60
      "
    volumes:
      - './scripts:/scripts'
    networks:
      ministack: {}
    depends_on:
      {%- for i in range(start=1, end=nomad_replicas+1) %}
      'nomad-server-{{ i }}':
        condition: service_healthy
      {%- endfor %}
  {%- endif %}
  {%- if services.consul.enabled %}
  post-start-consul:
    image: 'bash:5.2.37'
    container_name: 'post-start-consul'
    restart: unless-stopped
    command: |
      bash -c "
        apk add curl > /dev/null 2>&1
        echo ""
        bash /scripts/consul/01-apply-default-intension.sh
        {%- if plugins.traefik.enabled %}
        bash /scripts/consul/02-register-traefik.sh
        {%- endif %}
        sleep 60
      "
    volumes:
      - './scripts:/scripts'
    networks:
      ministack: {}
    depends_on:
      {%- for i in range(start=1, end=consul_replicas+1) %}
      'consul-server-{{ i }}':
        condition: service_healthy
      {%- endfor %}
  {%- endif %}
{%- endif %}
