scrape_configs:
  - job_name: 'consul-connect-envoy'
    consul_sd_configs:
    - server: 'consul-server-1:8500'
      scheme: 'http'
    relabel_configs:
    - source_labels: ['__meta_consul_service_metadata_envoy_metrics_port']
      action: 'keep'
      regex: '(.+)'
    - source_labels: ['__meta_consul_service']
      action: 'keep'
      regex: '(.+)-sidecar-proxy'
    - source_labels: ["__address__", "__meta_consul_service_metadata_envoy_metrics_port"]
      action: replace
      regex: (.+)(?::\d+);(\d+)
      replacement: $1:$2
      target_label: __address__
