{%- set consul_replicas = 1 -%}
{%- if services.consul.bootstrap_expect -%}
{%- set consul_replicas = services.consul.bootstrap_expect -%}
{%- endif -%}

{%- if services.consul.enabled %}
{%- set repository = "ghcr.io/gperreymond/hashibase" -%}
{%- if hashibase.repository -%}
{%- set repository = hashibase.repository -%}
{%- endif -%}
{%- set tag = "base-1.1.0" -%}
{%- if hashibase.tag -%}
{%- set tag = hashibase.tag -%}
{%- endif -%}
services:
  {%- for i in range(start=1, end=consul_replicas+1) %}
  consul-server-{{ i }}:
    image: '{{ repository }}:{{ tag }}'
    container_name: 'consul-server-{{ i }}'
    hostname: 'consul-server-{{ i }}'
    privileged: 'true'
    post_start:
      - command: 'start-ministack'
    pre_stop:
      - command: 'service consul stop'
    healthcheck:
      test: ["CMD", "consul-is-ready"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    environment:
      MINISTACK: 'true'
      {%- if services.consul.version %}
      CONSUL_VERSION: '{{ services.consul.version }}'
      {%- endif %}
    {%- if plugins.traefik.enabled %}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.consul.rule=Host(`consul.docker.localhost`)'
      - 'traefik.http.routers.consul.entrypoints=web'
      - 'traefik.http.services.consul.loadbalancer.server.port=8500'
    {%- endif %}
    volumes:
      - '../configurations/consul/config.hcl:/consul/config/config.hcl'
      - '../configurations/consul/server.hcl:/etc/consul.d/config/server.hcl'
      - 'consul_server_{{ i }}_data:/consul/data'
    networks:
      ministack:
        ipv4_address: '10.1.0.10{{ i }}'
  {%- endfor %}

volumes:
  {%- for i in range(start=1, end=consul_replicas+1) %}
  consul_server_{{ i }}_data: {}
  {%- endfor %}
{%- endif %}
