{%- set nomad_replicas = 1 -%}
{%- if services.nomad.bootstrap_expect -%}
{%- set nomad_replicas = services.nomad.bootstrap_expect -%}
{%- endif -%}

{%- set consul_replicas = 1 -%}
{%- if services.consul.bootstrap_expect -%}
{%- set consul_replicas = services.consul.bootstrap_expect -%}
{%- endif -%}

{%- if services.nomad.enabled %}
{%- set version = "1.0.0" -%}
{%- if hashibase.version -%}
{%- set version = hashibase.version -%}
{%- endif -%}
services:
  {%- set replicas = 1 -%}
  {%- if services.nomad.bootstrap_expect -%}
  {%- set replicas = services.nomad.bootstrap_expect -%}
  {%- endif -%}
  {%- for i in range(start=1, end=replicas+1) %}
  nomad-server-{{ i }}:
    image: 'ghcr.io/gperreymond/hashibase:base-{{ version }}'
    container_name: 'nomad-server-{{ i }}'
    hostname: 'nomad-server-{{ i }}'
    privileged: 'true'
    post_start:
      - command: 'start-ministack'
    pre_stop:
      - command: 'service nomad stop'
      {%- if services.consul.enabled %}
      - command: 'service consul stop'
      {%- endif %}
    healthcheck:
      {%- if services.nomad.customized.tls %}
      test: ["CMD", "curl", "--insecure", "-f", "https://10.1.0.20{{ i }}:4646/v1/status/leader"]
      {%- else %}
      test: ["CMD", "curl", "-f", "http://10.1.0.20{{ i }}:4646/v1/status/leader"]
      {%- endif %}
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    environment:
      MINISTACK: 'true'
      {%- if services.nomad.version %}
      NOMAD_VERSION: '{{ services.nomad.version }}'
      {%- endif %}
      {%- if services.consul.version %}
      CONSUL_VERSION: '{{ services.consul.version }}'
      {%- endif %}
      {%- if plugins.netbird.version %}
      NETBIRD_VERSION: '{{ plugins.netbird.version }}'
      {%- endif %}
    {%- if plugins.traefik.enabled %}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nomad.rule=Host(`nomad.docker.localhost`)'
      - 'traefik.http.routers.nomad.entrypoints=web'
      - 'traefik.http.services.nomad.loadbalancer.server.port=4646'
      {%- if services.nomad.customized.tls %}
      - 'traefik.http.services.nomad.loadbalancer.server.scheme=https'
      - 'traefik.http.services.nomad.loadbalancer.serverstransport=insecure@file'
      {%- endif %}
    {%- endif %}
    volumes:
      - '../configurations/nomad/config.hcl:/nomad/config/config.hcl'
      - '../configurations/nomad/base.hcl:/etc/nomad.d/config/00-base.hcl'
      - '../configurations/nomad/server.hcl:/etc/nomad.d/config/00-server.hcl'
      {%- if plugins.netbird.enabled and services.nomad.netbird.extra_envs %}
      - '../configurations/nomad/netbird.env:/netbird/config/config.env'
      {%- endif %}
      {%- if services.nomad.customized.enabled %}
      - '$HOME/.ministack/{{ name }}/nomad/server.hcl:/etc/nomad.d/config/01-server.hcl'
      {%- endif %}
      {%- if services.nomad.extra_volumes %}
      {%- for volume in services.nomad.extra_volumes %}
      - '$HOME/.ministack/{{ name }}/nomad/{{ volume }}:/{{ volume }}'
      {%- endfor %}
      {%- endif %}
      {%- if services.consul.enabled %}
      - '../configurations/consul/config.hcl:/consul/config/config.hcl'
      - '../configurations/consul/client.hcl:/etc/consul.d/config/client.hcl'
      {%- endif %}
      - 'nomad_server_{{ i }}_data:/nomad/data'
      {%- if services.consul.enabled %}
      - 'nomad_server_{{ i }}_consul_client_data:/consul/data'
      {%- endif %}
    networks:
      ministack:
        ipv4_address: '10.1.0.20{{ i }}'
    {%- if services.consul.enabled %}
    depends_on:
      {%- for i in range(start=1, end=consul_replicas+1) %}
      'consul-server-{{ i }}':
        condition: service_healthy
      {%- endfor %}
    {%- endif %}
  {%- endfor %}

volumes:
  {%- for i in range(start=1, end=nomad_replicas+1) %}
  nomad_server_{{ i }}_data: {}
  {%- if services.consul.enabled %}
  nomad_server_{{ i }}_consul_client_data: {}
  {%- endif %}
  {%- endfor %}
{%- endif %}
