{%- set network_subnet = "10.1.0.0" -%}
{%- if network.subnet -%}{%- set network_subnet = network.subnet -%}{%- endif -%}
{%- set hashibase_repository = "ghcr.io/gperreymond/hashibase" -%}
{%- if  hashibase.repository -%}{%- set hashibase_repository = hashibase.repository -%}{%- endif -%}
{%- set hashibase_tag = "base-1.2.0" -%}
{%- if  hashibase.tag -%}{%- set hashibase_tag = hashibase.tag -%}{%- endif -%}

{%- if services.nomad.clients %}
services:
  {%- for item in services.nomad.clients %}
  {%- set loop_index = loop.index -%}
  {%- if item.loop_index %}{%- set loop_index = item.loop_index %}{%- endif %}
  {{ datacenter }}-{{ item.name }}:
    image: '{{ hashibase_repository }}:{{ hashibase_tag }}'
    container_name: '{{ datacenter }}-{{ item.name }}'
    hostname: '{{ datacenter }}-{{ item.name }}'
    privileged: 'true'
    environment:
      MINISTACK: 'true'
      {%- if services.nomad.version %}
      NOMAD_VERSION: '{{ services.nomad.version }}'
      {%- endif %}
    post_start:
      - command: 'start-ministack'
    healthcheck:
      test: ["CMD", "nomad-is-ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - 'ministack/nomad=client'
      {%- if services.nomad.config.client.labels %}
      {%- for label in services.nomad.config.client.labels %}
      - '{{ label }}'
      {%- endfor %}
      {%- endif %}
      {%- if item.labels %}
      {%- for label in item.labels %}
      - '{{ label }}'
      {%- endfor %}
      {%- endif %}
    volumes:
      - '../configurations/nomad/config.hcl:/nomad/config/config.hcl'
      - '../configurations/nomad/base.hcl:/etc/nomad.d/config/00-base.hcl'
      - '../configurations/nomad/client.hcl:/etc/nomad.d/config/00-client.hcl'
      - '{{ item.name }}_data:/nomad/data'
      - '{{ item.name }}_docker_data:/var/lib/docker'
      # local volumes
      {%- if services.nomad.config.client.local_volumes %}
      {%- for volume in services.nomad.config.client.local_volumes %}
      - '../../{{ volume }}'
      {%- endfor %}
      {%- endif %}
      {%- if item.local_volumes %}
      {%- for volume in item.local_volumes %}
      - '../../{{ volume }}'
      {%- endfor %}
      {%- endif %}
      # docker volumes
      {%- if services.nomad.config.client.docker_volumes %}
      {%- for volume in services.nomad.config.client.docker_volumes %}
      - '{{ item.name }}_{{ volume }}:/mnt/{{ volume }}'
      {%- endfor %}
      {%- endif %}
      {%- if item.docker_volumes %}
      {%- for volume in item.docker_volumes %}
      - '{{ item.name }}_{{ volume }}:/mnt/{{ volume }}'
      {%- endfor %}
      {%- endif %}
    networks:
      ministack:
        ipv4_address: '{{ network_subnet | split(pat=".") | slice(start=0, end=3) | join(sep=".") }}.{{ 100 + loop_index }}'
  {%- endfor %}
{%- endif %}

{%- if services.nomad.clients %}
volumes:
  {%- for item in services.nomad.clients %}
  {{ item.name }}_data: {}
  {{ item.name }}_docker_data: {}
  # docker volumes
  {%- if services.nomad.config.client.docker_volumes %}
  {%- for volume in services.nomad.config.client.docker_volumes %}
  {{ item.name }}_{{ volume }}: {}
  {%- endfor %}
  {%- endif %}
  {%- if item.docker_volumes %}
  {%- for volume in item.docker_volumes %}
  {{ item.name }}_{{ volume }}: {}
  {%- endfor %}
  {%- endif %}
  {%- endfor %}
{%- endif %}
