#!/bin/bash

set -e

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --datasource) datasource="$2"; shift ;;
        *) echo "[ERROR] params not authorized" && exit 1;;
    esac
    shift
done

if [[ ! -f "build" ]]; then
    rm -rf build
fi

# export CONSUL_ENCRYPT_KEY=$(gomplate -i '{{ random.String 32 `[[:xdigit:]]` | base64.Encode }}')
gomplate \
  --input-dir=templates \
  --output-dir=build \
  --datasource config=$datasource
