#!/bin/bash

set -e

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --config) config="$2"; shift ;;
        *) echo "[ERROR] params not authorized" && exit 1;;
    esac
    shift
done

echo ""
echo "============================================================="
echo "[INFO] config file.................. $config"
echo "============================================================="
echo ""

if [[ ! -f "$config" ]]; then
  echo "[ERROR] config file '$config' not found."
  echo ""
  exit 1
fi

# TEMPLATES
./commands/subs/templates/generate --datasource $config
echo ""

# NETWORKS
./commands/subs/networks/create
echo ""

# COMPOSE
docker compose --file build/cluster.yaml up --detach --force-recreate
echo ""

# HASHISTACK
./commands/subs/services/start
echo ""
