{%- set nomad_replicas = 1 -%}
{%- if services.nomad.bootstrap_expect -%}
{%- set nomad_replicas = services.nomad.bootstrap_expect -%}
{%- endif -%}

{%- set consul_replicas = 1 -%}
{%- if services.consul.bootstrap_expect -%}
{%- set consul_replicas = services.consul.bootstrap_expect -%}
{%- endif -%}

{%- if services.nomad.enabled and services.nomad.clients %}
{%- set repository = "ghcr.io/gperreymond/hashibase" -%}
{%- if hashibase.repository -%}
{%- set repository = hashibase.repository -%}
{%- endif -%}
{%- set tag = "base-1.1.0" -%}
{%- if hashibase.tag -%}
{%- set tag = hashibase.tag -%}
{%- endif -%}
services:
  {%- for client in services.nomad.clients %}
  {{ client.name }}:
    image: '{{ repository }}:{{ tag }}'
    container_name: '{{ client.name }}'
    hostname: '{{ client.name }}'
    privileged: 'true'
    healthcheck:
      test: ["CMD", "nomad-is-ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    post_start:
      - command: 'start-ministack'
    pre_stop:
      - command: 'service nomad stop'
      {%- if services.consul.enabled %}
      - command: 'service consul stop'
      {%- endif %}
    environment:
      MINISTACK: 'true'
      {%- if services.nomad.version %}
      NOMAD_VERSION: '{{ services.nomad.version }}'
      {%- endif %}
      {%- if services.consul.version %}
      CONSUL_VERSION: '{{ services.consul.version }}'
      {%- endif %}
    volumes:
      - '../configurations/nomad/config.hcl:/nomad/config/config.hcl'
      - '../configurations/nomad/base.hcl:/etc/nomad.d/config/00-base.hcl'
      - '../configurations/nomad/client.hcl:/etc/nomad.d/config/00-client.hcl'
      {%- if services.nomad.customized.extra_configs %}
      - '$HOME/.ministack/{{ name }}/nomad/client.hcl:/etc/nomad.d/config/01-client.hcl'
      {%- endif %}
      {%- if client.extra_volumes %}
      {%- for volume in client.extra_volumes %}
      - '$HOME/.ministack/{{ name }}/nomad/{{ volume }}:/{{ volume }}'
      {%- endfor %}
      {%- endif %}
      {%- if services.consul.enabled %}
      - '../configurations/consul/config.hcl:/consul/config/config.hcl:ro'
      - '../configurations/consul/client.hcl:/etc/consul.d/config/client.hcl'
      {%- endif %}
      - 'nomad_client_{{ client.name }}_data:/nomad/data'
      - 'nomad_client_{{ client.name }}_docker_data:/var/lib/docker'
      {%- if services.consul.enabled %}
      - 'nomad_client_{{ client.name }}_consul_client_data:/consul/data'
      {%- endif %}
    networks:
      ministack:
        ipv4_address: '10.1.0.2{{ loop.index }}'
    depends_on:
      {%- for i in range(start=1, end=nomad_replicas+1) %}
      'nomad-server-{{ i }}':
        condition: service_healthy
      {%- endfor %}
      {%- if services.consul.enabled %}
      {%- for i in range(start=1, end=consul_replicas+1) %}
      'consul-server-{{ i }}':
        condition: service_healthy
      {%- endfor %}
      {%- endif %}
  {%- endfor %}

volumes:
  {%- for client in services.nomad.clients %}
  nomad_client_{{ client.name }}_data: {}
  nomad_client_{{ client.name }}_docker_data: {}
  {%- if services.consul.enabled %}
  nomad_client_{{ client.name }}_consul_client_data: {}
  {%- endif %}
  {%- endfor %}
{%- endif %}
