{%- if plugins.prometheus.enabled %}

{%- set nomad_replicas = 1 -%}
{%- if services.nomad.bootstrap_expect -%}
{%- set nomad_replicas = services.nomad.bootstrap_expect -%}
{%- endif -%}

{%- set consul_replicas = 1 -%}
{%- if services.consul.bootstrap_expect -%}
{%- set consul_replicas = services.consul.bootstrap_expect -%}
{%- endif -%}
global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s
{%- if 
  services.consul.enabled or
  services.nomad.enabled
%}
scrape_configs:
  {%- if services.nomad.enabled %}
  - job_name: 'nomad-server'
    honor_timestamps: true
    metrics_path: '/v1/metrics'
    scheme: http
    params: 
      format: ["prometheus"]  
    static_configs:
    - targets:
      {%- for i in range(start=1, end=nomad_replicas+1) %}
      - 'nomad-server-{{ i }}:4646'
      {%- endfor %}
  {%- endif %}
  {%- if services.consul.enabled %}
  - job_name: 'consul-server'
    honor_timestamps: true
    metrics_path: '/v1/agent/metrics'
    scheme: http
    params: 
      format: ["prometheus"]  
    static_configs:
    - targets:
      {%- for i in range(start=1, end=consul_replicas+1) %}
      - 'consul-server-{{ i }}:8500'
      {%- endfor %}
  - job_name: 'consul-connect-envoy'
    consul_sd_configs:
    - server: 'consul-server-1:8500'
      scheme: 'http'
    relabel_configs:
    - source_labels: ['__meta_consul_service_metadata_envoy_metrics_port']
      action: 'keep'
      regex: '(.+)'
    - source_labels: ['__meta_consul_service']
      action: 'keep'
      regex: '(.+)-sidecar-proxy'
    - source_labels: ["__address__", "__meta_consul_service_metadata_envoy_metrics_port"]
      action: replace
      regex: (.+)(?::\d+);(\d+)
      replacement: $1:$2
      target_label: __address__
  {%- endif %}
{%- endif %}
{%- endif %}
