{%- if plugins.prometheus.enabled %}
global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s

rule_files:
  - '/etc/prometheus/ministack/rules/*.yaml'
  - '/etc/prometheus/ministack/rules/*.yml'

scrape_config_files:
  - '/etc/prometheus/scrape_configs/*.yml'
  - '/etc/prometheus/ministack/scrape_configs/*.yaml'
  - '/etc/prometheus/ministack/scrape_configs/*.yml'
{%- endif %}
