#!/bin/bash

# get all running container IDs with the label "ministack.enable=true"
containers=$(docker ps --filter "label=ministack.enable=true" --format "{{.Names}}")

# Check if there are any containers with the label
if [[ -z "$containers" ]]; then
  echo "[WARN] no running containers with label 'ministack.enable=true' found."
  exit 0
fi

# iterate over each container and execute the command
for container in $containers; do
  echo "[INFO] executing 'start-ministack' on container: $container"
  docker exec -it "$container" start-ministack
  if [[ $? -ne 0 ]]; then
    echo "[ERROR] failed to execute command on container: $container"
  fi
done
